### ISSUE TITLE
Simple Process Check - Raising False Alarms 

### ISSUE THREAD

**Issue by rajpan** [scoutapp/scout-plugins#197] opened 2015-01-22 01:59 UTC
We have the simple process check plugin running on a lot of servers. But every once in a while it raises a alert mentioning that one of the processes are not running. But on the box these process have running for days together. It seems the logic for grepping the process errs outs for some reason. It hurts when these triggers alert mid -night and waking up to find no action required hurts. 

The logs are not available for what happened when the alert was raised because these run every minute. And these correct in the next few intervals without any user intervention or process restart.  

Eg - 
5:30 PM	
Process Check
Unique Processes met or dropped below 5 , dropping to 4 at 05:30PM

But all processes under monitoring was running from Jan 12. Please let us know what else can we provide to debug this issue.

**Comment by andre** [comment] 2015-01-22 19:02
@rajpan emailing you for more details.

**Comment by andre** [comment] 2015-01-26 17:29
Closing this issue: we believe the problem was caused by an older version of the plugin.

**Closed by andre** 2015-01-26 17:29 UTC
